### ISSUE TITLE
:markdown filter doesn't work in .jade files

### ISSUE THREAD

**Issue by wilsonminer** [static-dev/spike-core#101]
when the `:markdown` filter is used in a jade template, `rootsmini compile` complains with this error:

`In order to apply the transform markdown you must install one of "marked","supermarked","markdown-js","markdown"`

even when markdown and jstransformer-markdown are both installed locally.

**Comment by jenius** [comment]
- `npm i jstransformer-marked -S`
- Use `:marked` as the filter
- Profit!

**Comment by Leeds-eBooks** [comment]
FYI https://nodesecurity.io/advisories/101 `marked` has a security vulnerability and is no longer maintained, so this is unlikely to be fixed. I recommend using [Markdown-it](https://github.com/markdown-it/markdown-it) (I needed to pass it into my jade files as a local function).

**Comment by jenius** [comment]
Ah great call @Leeds-eBooks - thank you!

**Comment by wilsonminer** [comment]
@jenius: I actually started with that, but using :marked (or :markdown-it) as the filter (when the corresponding jstransformer package is installed) results in an error: `unknown filter ":marked"`.

**Comment by jenius** [comment]
Ok let me see if I can reproduce this with the latest version, if so I'll make sure it's patched up!

**Comment by jescalan** [comment]
So this definitely is an issue, we will have it patched as soon as we can!

**Comment by kylemac** [comment]
@wilsonminer appreciate your follow through with this one. thank you

**Comment by jescalan** [comment]
So this will be easily fixed once we upgrade from `jade` to `pug` by passing the filters manually into jade's options in `app.js`. Which honestly is a much better way to do it anyway. However `pug` is still on alpha releases, and while I expect a stable release soon I don't have an exact date for this.

**Comment by kylemac** [comment]
an example of this would be:

```js
// app.js
const md = require('markdown-it')

module.exports = {
  locals: {markdown: md}
}
```


```jade
//- index.jade
#content: markdown(myMarkdownContent)
```

**Comment by kylemac** [comment]
is there a alternate way to do this by configuring jade @jescalan ?

**Comment by jescalan** [comment]
Not that I'm aware of -- that looks like the best way we can run it with `jade`

**Comment by declandewet** [comment]
@kylemac if you really want to support the `:filter` syntax: Jade can use any [JSTransformer](https://github.com/jstransformers/jstransformer) as a filter, and it looks like there already is a [JSTransformer for `markdown-it`](https://github.com/jstransformers/jstransformer-markdown-it).

This is untested, but I think this would be the way to do it:

```js
const jade = require('jade')
const md = require('jstransformer-markdown-it')

jade.filters.markdown = md
```

There is more information here, especially regarding how this works in Pug: https://github.com/pugjs/pug/issues/2360

**Comment by kylemac** [comment]
i'll write a test fixture for that. given that we accepts jade opts in `app.js` this might already work, but just needs to be configured. it might be something worth adding to `roots-tpl-base` as well

**Comment by jescalan** [comment]
Now that we have switched to posthtml, I want to say that [this plugin](https://github.com/jonathantneal/posthtml-md) will provide a superior experience to jade-integrated markdown. I'm going to test this with the base template after the next release, and if this works, will close this issue out.

**Comment by wilsonminer** [comment]
Sounds good, thanks for the update. I for one will not miss jade! :)

**Comment by jescalan** [comment]
Haha well I think there is a little bit more work to be done on the core posthtml plugins you'll need ([example](https://github.com/posthtml/posthtml-exp/issues/2)), but eventually we should be able to replicate all of jade's functionality without jade itself if people just can't give up those closing tags 😛

**Comment by jescalan** [comment]
Closing this since we have removed jade, and markdown works nicely with reshape 😁
