### ISSUE TITLE
Jade > Pug

### ISSUE THREAD

**Issue by jescalan** [static-dev/spike-core#128]
As soon as there is a stable release of `pug` we should switch over from jade. When this happens, a lot of naming conventions and such will break. I think we should be well prepared for this before a stable release 😁

**Comment by kylemac** [comment]
any recent indications as to when that might be?

**Comment by jescalan** [comment]
This is the closest I've got! https://github.com/pugjs/pug/milestones/2.0.0%20-%20Modules%20and%20Plugins

They are definitely working actively on it...

**Comment by jescalan** [comment]
Ok so according to [this comment](https://github.com/pugjs/pug/issues/2184#issuecomment-176812678), an agreement was signed at the end of January saying that all `jade` naming would be eliminated entirely.

That means that there's somewhere around a month left before that point hits. I have to assume based on this that the rest of the changes are coming soon, which leads me to believe that we should have this prepared before stable launch so we don't immediately push a massively breaking change.

I'm going to prepare a branch that makes these changes, and a copy of our jade loaders that use pug.

**Comment by kylemac** [comment]
✅ https://github.com/static-dev/pug-static-loader
🔘 https://github.com/static-dev/pug-client-loader (wip)

**Comment by jescalan** [comment]
No visible progress in the last two weeks on pug, and no responses to suggestions that 1.x versions are published or to a question I asked about extremely rough timeline. I'm not sure how fast I see this getting finished, sadly.

The best solution by far would be if they published the latest jade release under `pug` in v1.x, but it doesn't seem like this is happening. Maybe we stick with jade, and the pug release is v2 for us?

**Comment by jescalan** [comment]
I'm going to swap this to backlog, since it doesn't seem like anything's happening soon. Will check back before a v1 release in case big movement has happened, but we cant bend our timeline around it. It will just be a major version when it happens. And if it happens through posthtml, it wont even need to be 😁

**Comment by kylemac** [comment]
yeah - same page

**Comment by jescalan** [comment]
This is no longer necessary to deal with in core after the update to posthtml. We'll have a smooth transition whenever it happens without any breaking changes, just an update to the base template.
