### ISSUE TITLE
Default extensions to `.css`, `.html`, `.js`

### ISSUE THREAD

**Issue by jescalan** [static-dev/spike-core#151]
Right now we use `jade`, `sss`, and `js`. But you don't have to use `sugarss`, in fact it's only present in our base template as a configurable option. If we switch to posthtml, you won't necessarily need to use jade and it will parse any form of html.

That being said, I do think we need to make these extensions configurable. Right now we have the `matchers` config, but it might be worth adding an easier shortcut option like `htmlExtensions: ['.html', '.jade']` etc. We need the extensions mostly for syntax highlighting and clarity when we're using a very different parser.

**Comment by kylemac** [comment]
i don't know if the shortcuts are any better. i need to think about that experience a little more
