### ISSUE TITLE
Image-webpack loader not passing through images

### ISSUE THREAD

**Issue by elvingm** [static-dev/spike-core#180]
In my `app.production.js`  I have tried the following configs for `image-webpack-loader` so it can optimize my images:

``` js
{ test: /\.(jpe?g|png|gif|svg)$/i, loader: 'source!image-webpack' }
```

``` js
{ test: /\.(jpe?g|png|gif|svg)$/i, loader: 'source-loader!image-webpack' }
```

``` js
{
    test: /\.(jpe?g|png|gif|svg)$/i,
    loaders: [
      'file?hash=sha512&digest=hex&name=[hash].[ext]',
       'image-webpack'
    ]
}
```

and with the `file-loader` as well as recommended by [image-webpack-loader docs](https://github.com/tcoopman/image-webpack-loader)

``` js
{
    test: /\.(jpe?g|png|gif|svg)$/i,
    loaders: [
      'file?hash=sha512&digest=hex&name=[hash].[ext]',
       'source!image-webpack'
    ]
}
```

In each case the only file that gets passed through is `favicon.ico` out of a list of images which contain jpg's, gif, png, and svgs.

**Comment by jescalan** [comment]
So the fix here is just to run it with `image-webpack` and no source loader 😁 Just a followup before closing!
