### ISSUE TITLE
README.md using wrong npms.io query string to query "spikeplugin"

### ISSUE THREAD

**Issue by garywu** [static-dev/spike-core#257]
## :zap: description

link for this line: "Spike Plugins for common integrations"
should use 
```
https://npms.io/search?q=spikeplugin
``` 

instead of 
```
https://npms.io/search?term=spikeplugin 
```

**Comment by jescalan** [comment]
Thanks for catching this! If you want to get credit for this fix, you could make a pull request to change it over ✨
