### ISSUE TITLE
easy isomorphism

### ISSUE THREAD

**Issue by kylemac** [static-dev/spike-core#70]
let it be on the record that i hate the term isomorphic, but it's common nomenclature these days. anyways, since we're in the fs, we know the paths you're writing to `public`, and we have access to our jade files as `clientTemplates` we can easily wrap your views in a router and do `pushState` style no-reload loading. 

it'd go a little something like:
- take all paths that you're exporting to `public` and define a "route" for them. we could use something like [page.js](https://visionmedia.github.io/page.js/) for routing
- inject some js that overrides hrefs
- have the router just run the jadeTpl.render and dump it on the page

we'd need to have the user define where (node/class/id) to inject in `app.js`

**Comment by kylemac** [comment]
thinking we could do [hot-module-replacement](https://webpack.github.io/docs/hot-module-replacement.html) for `roots.watch` as well.

**Comment by jescalan** [comment]
Shipped as https://github.com/static-dev/spike-pushstate

**Comment by dbox** [comment]
zomg 😻

**Comment by wkentdag** [comment]
👏 super excited about this feature!

**Comment by jescalan** [comment]
We tested it and it is super fast. Also have an article about it drafted 💖

**Comment by dbox** [comment]
📣  post it post it 🎉
