### ISSUE TITLE
support image optimization in core

### ISSUE THREAD

**Issue by kylemac** [static-dev/spike-core#91]
we could support https://github.com/tcoopman/image-webpack-loader in the core, and just have it turned off by default and then expose a constructor option like `imagemin: true` that you could turn on in prod (or whenever you felt like it)

there are drawbacks to including something like this in core, and a case could be made for it just to be part of `spike-base` so lets leave this issue here for discussion and things will come more into focus as we build out more projects with spike

**Comment by jescalan** [comment]
Closing in favor of an issue in the base template, since that's where this will be implemented.
